:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
:daemon: true

development:
  :concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 25